name: concepta
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # third-party libraries
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^4.0.3
  shimmer: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  pub_api_client: ^2.2.1

dev_dependencies:
  mocktail: ^0.3.0
  hive_generator: 1.1.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mockito: ^5.3.2

flutter:
  uses-material-design: true
